# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

require 'yaml'

boxes = YAML.load_file(File.join(File.dirname(__FILE__), 'inventory/vagrant.yml'))['all']['hosts']
#puts boxes

boxes.each do |name,opts|
   puts "#{name} = #{opts}"

   Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
     config.ssh.insert_key = false
     config.ssh.keys_only = true
     config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
     config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys" # 3
     config.vm.synced_folder '.', '/vagrant', disabled: true

     config.vm.define name do |machine|
       machine.vm.hostname = name
       machine.vm.box = opts["box"]
       machine.vm.network :private_network, ip: opts["ansible_ssh_host"], netmask:opts["netmask"]
       machine.vm.provision "shell", path: opts["skript"]
       #machine.vm.provision :ansible do |ansible|
        # Disable default limit to connect to all the machines
      #  ansible.limit = "all"
      #  ansible.playbook = "vagrant.yml"
      #end
    end
  end
end
