vagrant:
  vars:
    ansible_user: vagrant
    netmask: 255.255.0.0

  children:
    debian10:
      vars:
        box: generic/debian10
        provision: provision/vagrant/apt.sh
      hosts:
        vd1:
          ansible_host: 172.30.50.10
